### ISSUE TITLE
[General Issue]: Resetting the rank to 1000 at the end of a season

### ISSUE THREAD

**Issue by TimAurory** [Aurory-Game/aurory-issues#49]
### Contact Details

AuroTim #9909

### Description

With the end of season 1, every players have gotten their rank settled back to 1000 points. It's too hard for beginners to play while great players are around their ELO. 

It would probably be a good idea to reset the rank by x% rather than putting every players to the same level. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jp** [comment]
The ranking algorithm we use is pretty quick to set the players to their good ranks.

Some game are using ranking algorithms which are less based on statistic research, they are for example incrementing/decrementing with a static number (ex: +10 on a win, -10 on a loss for everybody). Generally in these game, it takes a very long time to reach the appropriate rank. For this reason, on a new season they tend to move back the players rank rather than giving a full reset.

The statistic model we use is not meant to be manually manipulated, it will inevitably lead to unfair scores and matches. This is a no-go to drop the rank of all players by a specific percentage or number.

Currently, no rework is planned for the ranking system. Changing it would require massive efforts and inherent risks to have a fully broken ranking and matchmaking for everybody. We need to focus on the more important topics.

**Comment by jp** [comment]
Closing this as not planned.
