### ISSUE TITLE
[Bug]: Damage discrepancy

### ISSUE THREAD

**Issue by rekthoneybadger** [Aurory-Game/aurory-issues#77]
### Contact Details

RektHoneyBadger#6944

### What happened?

Used Scaring Strike on N9 with below 300HP,hit him with Bitebit right after like 8 or 9 times for around 20 damage per hit,he survived and had more than 100HP left,it felt like i was hitting through a rock,normally with that ammount of catrenaline built he dies even if he is full HP,i had 77% Attack and he had around 90 defense i think.math doesn't make any sense..

### Steps to reproduce

...

### Expected Behavior

He should have been dead and overkilled

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by EvanxQA** [comment]
@rekthoneybadger Can you please include a screenshot of the Battle ID in which this issue occurred so that we can look into this? At the moment we have no reason to believe that bitebit is doing less damage than intended, so I'd have to look into your specific battle to determine if there's an issue here or not. 

If you don't have one, can you try and provide a screenshot of the Battle ID next this issue occurs?
